apiVersion: theia.cloud/v3beta
kind: AppDefinition
metadata:
  name: cdt-cloud-demo
  namespace: theiacloud
spec:
  name: cdt-cloud-demo
  image: theiacloud/cdt-blueprint
  pullSecret: ""
  uid: 101
  port: 3000
  {{- if .Values.hosts.usePaths }}
  host: {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
  {{- else }}
  host: {{ tpl (.Values.hosts.instance | toString) . }}
  {{- end }}
  ingressname: {{ tpl (.Values.ingress.instanceName | toString) . }}
  minInstances: 0
  maxInstances: 10
  timeout:
    limit: 30
    strategy: FIXEDTIME
  requestsMemory: 500M
  limitsMemory: 1200M
  requestsCpu: "100m"
  limitsCpu: "2"
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: "/home/project/persisted"
